name: Build and Publish Docker Image

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v4
        with:
          images: ${{ GITHUB.REPOSITORY }}
        id: meta
      - uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ${{ steps.meta.outputs.tags }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push ${{ steps.meta.outputs.tags }}
